function setSettings() {
  SETTINGS = {
    PRODUCTION: {
      SPREADSHEET_ID: "PUT GOOGLE SPREADSHEET ID HERE",
      ERROR_ALERT_EMAIL_ADDRESS: "PUT EMAIL FOR ERROR ALERTS HERE",
    },
    TEST: {
      SPREADSHEET_ID: "PUT TEST GOOGLE SPREADSHEET ID HERE",
      ERROR_ALERT_EMAIL_ADDRESS: "PUT EMAIL FOR TEST ERROR ALERTS HERE",
    },
    TRANSACTIONS_SHEET_NAME: "Transactions",
    ALERT_MESSAGE_GMAIL_LABEL: "bankupdate",
  };
  Object.freeze(SETTINGS);
}
